version: "3"
services:
  app:
    build: .
    ports:
      - "$APP_HTTP_HOST_PORT:8080"
      - "$APP_DEBUG_HOST_PORT:8000"
    environment:
      - 'JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n" -XX:+UnlockExperimentalVMOptions --enable-preview'
      - "DATABASE_HOST_NAME=$DATABASE_HOST_NAME"
      - "DATABASE_PORT=$DATABASE_HOST_PORT"
      - "PGUSER=biblivre"
      - "PGPASSWORD=$POSTGRES_PASSWORD"
      - "PGDATABASE=$POSTGRES_DB"
      - "DIGITAL_MEDIA_DAO_IMPL=$DIGITAL_MEDIA_DAO_IMPL"
      - "SPRING_MAIL_HOST=$SPRING_MAIL_HOST"
      - "SPRING_MAIL_PORT=$SPRING_MAIL_PORT"
      - "SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME"
      - "SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD"
    depends_on:
      - database
  database:
    image: postgres:12-alpine
    ports:
      - "$DATABASE_HOST_PORT:$POSTGRES_DEFAULT_PORT"
    volumes:
      - "./sql/biblivre4.sql:/docker-entrypoint-initdb.d/populate-initial-data.sql"
    environment:
      - "POSTGRES_USER=biblivre"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_DB=$POSTGRES_DB"
  web:
    image: nginx
    ports:
      - "$WEB_HTTP_HOST_PORT:80"
    volumes:
      - "./nginx/conf.d/:/etc/nginx/conf.d/"
    depends_on:
      - app
