openapi:
  biblivreREST:
    base-path: /api/v2
logging:
  level:
    org:
server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true