package biblivre.swagger.configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@jakarta.annotation.Generated(
        value = "io.swagger.codegen.v3.generators.java.SpringCodegen",
        date = "2024-04-07T11:01:49.151127865Z[GMT]")
@Configuration
public class SwaggerDocumentationConfig {

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI()
                .info(
                        new Info()
                                .title("Biblivre REST API")
                                .description(
                                        "No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)")
                                .termsOfService("")
                                .version("0.0.1")
                                .license(new License().name("").url("http://unlicense.org"))
                                .contact(new io.swagger.v3.oas.models.info.Contact().email("")));
    }
}
