import { UserSearchableFieldTypeEnum } from '../../generated-sources'

import type { UserSearchableField } from '../../generated-sources'

export const userFieldsFixture: UserSearchableField[] = [
  {
    key: 'email',
    type: UserSearchableFieldTypeEnum.String,
    required: true,
    maxLength: 0,
    sortOrder: 1,
  },
  {
    key: 'gender',
    type: UserSearchableFieldTypeEnum.List,
    required: false,
    maxLength: 2,
    sortOrder: 2,
  },
  {
    key: 'phone_cel',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 25,
    sortOrder: 3,
  },
  {
    key: 'phone_home',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 25,
    sortOrder: 4,
  },
  {
    key: 'phone_work',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 25,
    sortOrder: 5,
  },
  {
    key: 'phone_work_extension',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 10,
    sortOrder: 6,
  },
  {
    key: 'id_rg',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 20,
    sortOrder: 7,
  },
  {
    key: 'id_cpf',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 20,
    sortOrder: 8,
  },
  {
    key: 'address',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 500,
    sortOrder: 9,
  },
  {
    key: 'address_number',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 100,
    sortOrder: 10,
  },
  {
    key: 'address_complement',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 100,
    sortOrder: 11,
  },
  {
    key: 'address_zip',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 20,
    sortOrder: 12,
  },
  {
    key: 'address_city',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 100,
    sortOrder: 13,
  },
  {
    key: 'address_state',
    type: UserSearchableFieldTypeEnum.String,
    required: false,
    maxLength: 100,
    sortOrder: 14,
  },
  {
    key: 'birthday',
    type: UserSearchableFieldTypeEnum.Date,
    required: false,
    maxLength: 0,
    sortOrder: 15,
  },
  {
    key: 'obs',
    type: UserSearchableFieldTypeEnum.Text,
    required: false,
    maxLength: 0,
    sortOrder: 1002,
  },
]
